#!/usr/bin/python
# -*- coding: utf-8 -*-

from ForceDrive import ForceDrive
import rospy
import math
import rospy; import actionlib; from control_msgs.msg import FollowJointTrajectoryGoal, FollowJointTrajectoryAction; from actionlib import SimpleActionClient, GoalStatus; from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

angle = math.pi / 2
angular_velocity = 0.5

def cycle():
    # @ Beer
    #whole_body.move_to_joint_positions({"arm_flex_joint": -0.5, "arm_roll_joint": -0.3, "arm_lift_joint": 0.1})
    #gripper.command(-0.25)

    # retract
    #whole_body.move_to_joint_positions({"arm_flex_joint": -0.0, "arm_roll_joint": 0})

    # turn
    fd.drive(0, 0, angular_velocity, abs(angle / angular_velocity))

    # Place in basket
    #whole_body.move_to_joint_positions({"arm_flex_joint": -0.5, "arm_roll_joint": -0.3, "arm_lift_joint": 0.1})
    #gripper.command(1.2)

    # retract
    #whole_body.move_to_joint_positions({"arm_flex_joint": -0.0, "arm_roll_joint": 0})

    # turn back
    fd.drive(0, 0, -angular_velocity, abs(angle / angular_velocity))

import rospy

from dynamic_reconfigure.server import Server
from tue_hsr.cfg import ArmConfig

rospy.init_node("test", anonymous = True)
ac = actionlib.SimpleActionClient('/hsrb/arm_trajectory_controller/follow_joint_trajectory', FollowJointTrajectoryAction)

def callback(config, level):
    joint_names = ['arm_roll_joint', 'arm_lift_joint', 'arm_flex_joint', 'wrist_flex_joint', 'wrist_roll_joint']
    positions = []
    for joint_name in joint_names:
        positions.append(config[joint_name])
        
    ac.send_goal_and_wait(FollowJointTrajectoryGoal(trajectory=JointTrajectory(joint_names=joint_names, points=[JointTrajectoryPoint(positions=positions, time_from_start=rospy.Duration(1))]), goal_time_tolerance=rospy.Duration(10)))
    return config

srv = Server(ArmConfig, callback)
rospy.spin()
